name: myweb
description: Flutter web admin panel project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (Web compatible & null-safe)
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # Utilities (null-safe)
  file_picker: ^8.0.0
  intl: ^0.20.2
  archive: ^3.4.0
  xml: ^6.6.1
  url_launcher: ^6.2.6
  web: ^1.1.1
  universal_html: ^2.0.10
  pdf: ^3.11.3
  file_saver: ^0.1.0
  flutter_svg: ^2.2.3
  cloudinary_public: ^0.23.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
